Make e2e into two jobs so previous runs don't get overriden

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -220,8 +220,8 @@ jobs:
         shell: 'pwsh'
         run: 'npm run test:integration:sandbox:none'
 
-  e2e:
-    name: 'E2E'
+  e2e_nonfork:
+    name: 'E2E (Non-fork)'
     needs:
       - 'e2e_linux'
       - 'e2e_mac'
@@ -229,7 +229,33 @@ jobs:
     if: |
       always() &&
       (needs.merge_queue_skipper.outputs.skip == 'false' &&
-      !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository))
+      !(github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository))
+    runs-on: 'gemini-cli-ubuntu-16-core'
+    steps:
+      - name: 'Check E2E test results'
+        run: |
+          if [[ ${{ needs.e2e_linux.result }} == 'skipped' || \
+               ${{ needs.e2e_mac.result }} == 'skipped' ]]; then
+            echo "E2E tests were skipped, please run them before submission"
+            exit 1
+          fi
+          if [[ ${{ needs.e2e_linux.result }} != 'success' || \
+               ${{ needs.e2e_mac.result }} != 'success' ]]; then
+            echo "One or more E2E jobs failed."
+            exit 1
+          fi
+          echo "All required E2E jobs passed!"
+
+  e2e_fork:
+    name: 'E2E (Forks)'
+    needs:
+      - 'e2e_linux'
+      - 'e2e_mac'
+      - 'merge_queue_skipper'
+    if: |
+      always() &&
+      (needs.merge_queue_skipper.outputs.skip == 'false' &&
+      github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository)
     runs-on: 'gemini-cli-ubuntu-16-core'
     steps:
       - name: 'Check E2E test results'
